### ISSUE TITLE
Stop rerender of p5 component when redux variables update

### ISSUE THREAD

**Issue by DjCrqss** [jamesrweb/react-p5-wrapper#284] opened 2023-11-07 08:21 UTC
Hi there,

Sorry, I have been looking at all the documentation and examples (though many of the ones in the closed issues are deleted) and I can't solve this and I can't seem to lift the state out of my component so that redux does not re-render it.

I have this main p5 function with part of the problematic code:

```
export default function Renderer() {
  ....
  const {mapScale, windowHeight, windowWidth, panX, panY} = useSelector((state) => state.client); // from redux
  ....
  const options = (p5) => {
     const zoomSlider = p5.createSlider(1, 4, mapScale, 0.1);
        zoomSlider.input(() => {
            dispatch(updateScale(zoomSlider.value()));
            resizeRenderer(p5);
            p5.resizeCanvas(windowWidth, windowHeight);
        });
        ...
  }
  
  ...
  
  const sketch = (p5) => {
     // setup and draw is here
     // drawing of map is related to the scaling variables
  }
  
  return (
        <ReactP5Wrapper sketch={sketch} />
    );
}
```
and in the redux clientSlice.js
```
export const worldSlice = createSlice({
    name: "world",
    initialState: {
        // world zooming
        mapScale: userSettings.mapScale || 1,
        windowHeight: 0,
        windowWidth: 0,
        // world panning
        panX: 0,
        panY: 0,
    },
    reducers: {
        updateScale: (state, action) => {
            state.mapScale = action.payload;
        },
        updateHeight: (state, action) => {
            state.windowHeight = action.payload;
        },
        updateWidth: (state, action) => {
            state.windowWidth = action.payload;
        },
        updatePanX: (state, action) => {
            state.panX = action.payload;
        },
        updatePanY: (state, action) => {
            state.panY = action.payload;
        },
    },
});

// Export the actions and the slice reducer
export const { updateScale, updateHeight, updateWidth, updatePanX, updatePanY } = worldSlice.actions;
export default worldSlice.reducer;
```

I found out this is an issue as when I drag the slider, the component rerenders, meaning I lose focus on the slider straight away

Thanks in advance!

**Comment by DjCrqss** [comment] 2023-11-07 08:23
I tried lifting it out like so (partial code snippet)

```
    export default function Renderer() {
    // Redux store
    const background = useSelector((state) => state.world.background);
    const images = useSelector((state) => state.images.loadedImages);
    const unloadedImages = useSelector((state) => state.images.unloadedImages);
    const editorMode = useSelector((state) => state.client.editorMode);
    const {mapScale, windowHeight, windowWidth, panX, panY} = useSelector((state) => state.client);
    const dispatch = useDispatch();

    // get user setttings fil;
    const userSettings = require('../assets/world/settings.json');

    // state variables
    const EDITOR_GRID = {
        // editor grid size
        // TODO: move to worldSlice
        x: userSettings.gridColumns || 56,
        y: userSettings.gridRows || 36,
        tilesize: userSettings.tileSize || 6,
        // editor bounds
        left: -1,
        right: -1,
        top: -1,
        bottom: -1,
    }
    return (
        <ReactP5Wrapper sketch={sketch} background={background}
            editorMode={editorMode} mapScale={mapScale} windowHeight={windowHeight} windowWidth={windowWidth} panX={panX} panY={panY}
            EDITOR_GRID={EDITOR_GRID} images={images} unloadedImages={unloadedImages} dispatch={dispatch}
            />
    );
}


// The P5.js sketch
const sketch = (p5) => {
    // state variables
    let EDITOR_GRID = {
        // editor grid size
        // TODO: move to worldSlice
        x: 56,
        y: 36,
        tilesize:  6,
        // editor bounds
        left: -1,
        right: -1,
        top: -1,
        bottom: -1,
    }
    let mapScale = 0;
    let windowHeight = 0;
    let windowWidth = 0;
    let panX = p5.panX;
    let panY = p5.panY;
    let background = [];
    let images = [];
    let unloadedImages = [];
    let editorMode = p5.editorMode;
    let dispatch = ()=>{};
    
    let unloadedImagesCooldown = -1;


    p5.updateWithProps   = (newProps) => {
        EDITOR_GRID = newProps.EDITOR_GRID;
        mapScale = newProps.mapScale;
        windowHeight = newProps.windowHeight;
        windowWidth = newProps.windowWidth;
        panX = newProps.panX;
        panY = newProps.panY;
        background = newProps.background;
        images = newProps.images;
        unloadedImages = newProps.unloadedImages;
        editorMode = newProps.editorMode;
        dispatch = newProps.dispatch;
    }

   ....

   rest of functions for drawing and updating

   ...
}

```

however either still seems to reupdate or freezes (possibly due to recursive calls)

**Comment by DjCrqss** [comment] 2023-11-07 23:31
Nevermind, did do it!! Found an issue that storing p5js image objects into arrays in global contexts (redux or react createContext) will cause the app to freeze upon resizing the window. Had to make the p5.load'd images now stored in the same file as the sketch and it seems fine

**Comment by jamesrweb** [comment] 2023-11-20 12:35
Closed as the issue is not a library problem and is now resolved.

**Closed as completed by jamesrweb** 2023-11-20 12:35 UTC
